// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vyipfackuypaufzutzwi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ5aXBmYWNrdXlwYXVmenV0endpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjUxNzUsImV4cCI6MjA2NDgwMTE3NX0.TH7Q67UZX-Qk5jodNjZiFmvLxO6qibsuqmt5YqkjoGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);